---
- name: Site Down
  hosts: all
  connection: local
  gather_facts: false
  become: true
  tasks:
    - debug:
        msg: "Website is down!"

    - name: Restart Apache service
      ansible.builtin.systemd:
        name: httpd.service
        state: restarted
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'
        or
        ansible_distribution == 'Fedora'
        
    - name: Restart Apache service
      ansible.builtin.systemd:
        name: apache2.service
        state: restarted
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'

