---
- name: OpenShift Alertmanager Test Rulebook
  hosts: all
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5050
        data_host_path: ""
        
  rules:
    - name: OpenShift Alertmanager Debug
      condition: event.alert is defined
      action:
        #debug: 
        #  msg: "Alert defined! Alert is: {{ event.alert.status }} and Type is: {{ event.alert.labels.alertname }}"
        run_job_template:
          name: OpenShift Alertmanager Firing Quarkus Resolution
          organization: Default
