---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
     - ansible.eda.url_check:
        urls:
          - http://192.168.1.94
        delay: 10

  rules:
    ## Define the conditions we are looking for 
    - name: Web site is up
      condition: event.url_check.status == "up"
    ## Define the action we should take should the condition be met  
      action:
        run_playbook:
          name: wowza.yml

    - name: Web site is down
      condition: event.url_check.status == "down"
    ## Define the action we should take should the condition be met  
      action:
        run_job_template:
          name: fix_web
          organization: Default
