---
- name: Zabbix Rulebook Events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:          
    - name: Zabbix Apache is Down Event on "{{ event.payload.host_host }}"
      condition: event.payload.trigger_id == 32999 and event.payload.trigger_name is regex("Apache.*Service is down")
      action:
        run_job_template:
          name: Restart Apache Web Server
          organization: Default
          job_args:
            limit: "{{ event.payload.host_host }}"
            
    - name: Zabbix High Memory Utilization Event on "{{ event.payload.host_host }}"
      condition: event.payload.trigger_id == 32704 and event.payload.trigger_name is regex("Linux.*High memory utilization")
      action:
        debug: 
          msg: "Event triggered!: {{ event.payload.event_name }} and Operation: {{ event.payload.operation_data }} on Server: {{ event.payload.host_host }}"

 #   - name: Zabbix Space is critically low on "{{ event.payload.host_host }}"
 #     condition: event.payload.trigger_id == 33019 and event.payload.trigger_name is regex("Linux.*Space is critically low")
 #     action:
 #       debug: 
 #         msg: "Event triggered!: {{ event.payload.event_name }} and Operation: {{ event.payload.operation_data }} on Server: {{ event.payload.host_host }}"
 
    - name: Zabbix Space is critically low on "{{ event.payload.host_host }}"
      condition: event.payload.trigger_id == 33019 and event.payload.trigger_name is regex("Linux.*Space is critically low")
      action:
        run_job_template:
          name: Fix Low Disk Space Alert
          organization: Default
          job_args:
            limit: "{{ event.payload.host_host }}"
