---
- name: Zabbix Test Rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Debug
      condition: event.payload is defined
      action:
        debug: 
          msg: "Payload defined!"
          
    - name: Zabbix Webhook event
      condition: event.payload.event_name == "Apache service is down"
      action:
        run_job_template:
          name: Restart Apache Web Server
          organization: Default
          job_args:
            limit: "{{ event.payload.host_host }}"
