---
- name: Fix low disk space alert
  hosts: all
  tasks:

  - name: Remove /root/archivo_grande.bin if it exists
    ansible.builtin.file:
      path: /root/archivo_grande.bin
      state: absent
    become: true
